# .___  _                     .                     .       __               .        _
# /   \ /        ___  , __   _/_     __.  , _ , _   /       |    __.  .___   |     ___/   ____
# |,_-' |,---.  /   ` |'  `.  |    .'   \ |' `|' `. |       |  .'   \ /   \  |    /   |  (
# |     |'   ` |    | |    |  |    |    | |   |   | |  /\   /  |    | |   '  |   ,'   |  `--.
# /     /    | `.__/| /    |  \__/  `._.' /   '   / |,'  \,'    `._.' /     /\__ `___,' \___.'

name: 'PhantomWorlds'
version: '${project.version}'
description: '${project.description}'
authors: ['lokka30']
website: 'https://github.com/lokka30/PhantomWorlds'

main: 'me.lokka30.phantomworlds.PhantomWorlds'
api-version: '1.13'
load: 'POSTWORLD'

commands:
  phantomworlds:
    description: 'Create, manage or teleport to worlds.'
    aliases: ['pw', 'world']
    usage: '/<command>'

permissions:
  phantomworlds.*:
    default: op
    description: 'All PhantomWorlds permissions, ideally given to administrators.'
    children:
      phantomworlds.knows-vanished-users: true
      phantomworlds.command.phantomworlds.*: true

  phantomworlds.knows-vanished-users:
    default: op
    description: 'Users with this permission will ignore the status of vanished players when using commands from PhantomWorlds, such as in tab-completion suggestions.'

  phantomworlds.command.phantomworlds.*:
    default: op
    description: 'Ability to run all /pw commands.'
    children:
      phantomworlds.command.phantomworlds: true
      phantomworlds.command.phantomworlds.compatibility: true
      phantomworlds.command.phantomworlds.create: true
      phantomworlds.command.phantomworlds.debug: true
      phantomworlds.command.phantomworlds.info: true
      phantomworlds.command.phantomworlds.list: true
      phantomworlds.command.phantomworlds.setspawn: true
      phantomworlds.command.phantomworlds.teleport: true
      phantomworlds.command.phantomworlds.spawn: true
      phantomworlds.command.phantomworlds.unload: true
      phantomworlds.command.phantomworlds.reload: true

  phantomworlds.command.phantomworlds:
    default: op
    description: 'Ability to run /pw'

  phantomworlds.command.phantomworlds.compatibility:
    default: op
    description: 'Ability to run /pw compatibility'

  phantomworlds.command.phantomworlds.debug:
    default: op
    description: 'Ability to run /pw debug'

  phantomworlds.command.phantomworlds.create:
    default: op
    description: 'Ability to run /pw create'

  phantomworlds.command.phantomworlds.info:
    default: true
    description: 'Ability to run /pw info'

  phantomworlds.command.phantomworlds.list:
    default: op
    description: 'Ability to run /pw list'

  phantomworlds.command.phantomworlds.setspawn:
    default: op
    description: 'Ability to run /pw setspawn'

  phantomworlds.command.phantomworlds.teleport:
    default: op
    description: 'Ability to run /pw teleport'

  phantomworlds.command.phantomworlds.spawn:
    default: op
    description: 'Ability to run /pw spawn'

  phantomworlds.command.phantomworlds.unload:
    default: op
    description: 'Ability to run /pw unload'

  phantomworlds.command.phantomworlds.reload:
    default: op
    description: 'Ability to run /pw reload'
